#!/usr/bin/env python3
"""Generate the firmware-owned default schema for the Systeemrecorder.

Single source of truth: `openquatt/web/js/src/core/config.js`
(`ENTITY_DEFS` + `DEBUG_RECORDING_KEYS`).

Output: `components/openquatt_debug_recorder/debug_recorder_default_fields.h`
as an X-macro list:

    OQ_DEBUG_RECORDER_DEFAULT_FIELD("key", "domain", "name")

The firmware resolves each entry against the ESPHome entities at boot, so a
cold boot without an open web app still builds recording history. Entries
whose entity does not exist on the running topology are skipped as missing.

Usage:
    python3 scripts/generate_debug_recorder_default_fields.py [--check]

With `--check` the script exits non-zero when the committed `.inc` file is
out of sync (used by the contract test).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_JS = ROOT / "openquatt" / "web" / "js" / "src" / "core" / "config.js"
OUTPUT = ROOT / "components" / "openquatt_debug_recorder" / "debug_recorder_default_fields.h"

SUPPORTED_DOMAINS = {
    "sensor",
    "number",
    "binary_sensor",
    "switch",
    "text_sensor",
    "select",
}


def parse_domain_constants(source: str) -> dict[str, str]:
    """Resolve DOMAIN_* identifiers to their string value."""
    mapping = {}
    for match in re.finditer(r'const\s+(DOMAIN_[A-Z_]+)\s*=\s*"([^"]+)"\s*;', source):
        mapping[match.group(1)] = match.group(2)
    return mapping


def parse_entity_defs(source: str, domain_constants: dict[str, str]) -> dict[str, tuple[str, str]]:
    """Parse createEntityDefinitions entries: [key, domain, name, optional?]."""
    block_match = re.search(
        r"export const ENTITY_DEFS = createEntityDefinitions\(\[(.*?)\]\);",
        source,
        re.S,
    )
    if block_match is None:
        raise ValueError("ENTITY_DEFS block not found in config.js")
    block = block_match.group(1)
    entries: dict[str, tuple[str, str]] = {}
    pattern = re.compile(
        r'\[\s*"((?:[^"\\]|\\.)+)"\s*,\s*(DOMAIN_[A-Z_]+|"[^"]+")\s*,\s*"((?:[^"\\]|\\.)+)"'
    )
    for match in pattern.finditer(block):
        key = match.group(1)
        domain_token = match.group(2)
        name = match.group(3)
        if domain_token.startswith('"'):
            domain = domain_token.strip('"')
        else:
            domain = domain_constants.get(domain_token, "")
        entries[key] = (domain, name)
    return entries


def parse_recording_keys(source: str) -> list[str]:
    match = re.search(r"export const DEBUG_RECORDING_KEYS = \[(.*?)\];", source, re.S)
    if match is None:
        raise ValueError("DEBUG_RECORDING_KEYS not found in config.js")
    return re.findall(r'"([^"]+)"', match.group(1))


def c_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render(entries: list[tuple[str, str, str]]) -> str:
    lines = [
        "// Generated by scripts/generate_debug_recorder_default_fields.py.",
        "// Do not edit manually. Source of truth: openquatt/web/js/src/core/config.js",
        "// (ENTITY_DEFS + DEBUG_RECORDING_KEYS).",
        f"// Field count: {len(entries)}.",
        "// This file is intentionally inert unless OQ_DEBUG_RECORDER_DEFAULT_FIELD",
        "// is defined by the includer: ESPHome includes every component header",
        "// from esphome.h, where the macro is not defined.",
        "// clang-format off: generated X-macro list, stable by construction.",
        "#ifdef OQ_DEBUG_RECORDER_DEFAULT_FIELD",
    ]
    for key, domain, name in entries:
        lines.append(
            f'OQ_DEBUG_RECORDER_DEFAULT_FIELD("{c_escape(key)}", "{c_escape(domain)}", "{c_escape(name)}")'
        )
    lines.append("#endif  // OQ_DEBUG_RECORDER_DEFAULT_FIELD")
    lines.append("// clang-format on")
    return "\n".join(lines) + "\n"


def build() -> str:
    source = CONFIG_JS.read_text(encoding="utf-8")
    domain_constants = parse_domain_constants(source)
    entity_defs = parse_entity_defs(source, domain_constants)
    keys = parse_recording_keys(source)
    entries: list[tuple[str, str, str]] = []
    for key in keys:
        if key not in entity_defs:
            raise ValueError(f"DEBUG_RECORDING_KEYS entry {key!r} has no ENTITY_DEFS definition")
        domain, name = entity_defs[key]
        if domain not in SUPPORTED_DOMAINS:
            raise ValueError(f"Unsupported recorder domain {domain!r} for key {key!r}")
        entries.append((key, domain, name))
    return render(entries)


def main(argv: list[str]) -> int:
    content = build()
    field_lines = sum(
        1 for line in content.splitlines() if line.startswith("OQ_DEBUG_RECORDER_DEFAULT_FIELD(")
    )
    if "--check" in argv:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT} is out of sync; run the generator without --check")
            return 1
        print(f"{OUTPUT} is in sync ({field_lines} fields)")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({field_lines} fields)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
