#!/usr/bin/env python3
"""Rebuild the V2 heating model from the EXACT supplied CiC 4.2.0 ELF.

Python 3.10+, standard library. No network, flashing, or repository writes.
The row map follows the constructor's memcpy order, NOT consecutive literals.
See docs/research/issue-667-v2-model-correction.md and
scripts/research/verify_v2_constructor.py.
"""
from __future__ import annotations
import argparse, csv, hashlib, json, math, struct
from pathlib import Path

ELF_SHA256 = '3f04ba2bed6c4ec1b4215482f4213e8ea7475c98c305712973b8035838c717b6'
MODEL_ID = 'oq-v2-heating-cic420-r1'
FREQ = [20, 26, 30, 48, 55, 61, 72, 80, 85, 90]
AMB = [-15, -5.000001, -5, -.000001, 0, 4.999999, 5, 10.999999, 11, 13.999999, 14, 18.999999, 19, 23, 26.999999, 27, 44.99]
SUP = [18, 25, 35, 45, 54.999999, 55, 65, 70]
ROW_MAP = [list(range(i * 17, (i + 1) * 17)) for i in range(5)] + [
    [85,86,86,87,87,88,88,89,90,78,78,79,80,81,82,83,84],
    [91,92,92,93,93,94,94,95,96,97,97,98,99,100,101,102,103],
    [104,105,105,106,106,107,107,108,109,110,110,111,112,113,114,115,116],
]

def extract(elf: Path) -> dict:
    blob = elf.read_bytes()
    if hashlib.sha256(blob).hexdigest() != ELF_SHA256:
        raise ValueError('ELF SHA256 mismatch; offsets are valid only for the supplied CiC 4.2.0 build.')
    for fmt, offset, expected in [('10H',0x200588,FREQ), ('17d',0x2005a0,AMB), ('8d',0x200628,SUP)]:
        if list(struct.unpack_from('<'+fmt,blob,offset)) != expected:
            raise ValueError(f'Unexpected axis at {offset:#x}')
    def surface(offset: int) -> list:
        return [[[None if math.isnan(v) else v for v in struct.unpack_from('<10d',blob,offset+80*r)]
                 for r in supply] for supply in ROW_MAP]
    power, cop = surface(0x200668), surface(0x202af8)
    paired = [(p,c) for pp,cc in zip(power,cop) for pr,cr in zip(pp,cc) for p,c in zip(pr,cr)]
    if len(paired) != 1360 or sum(p is not None for p,c in paired) != 590:
        raise ValueError('Unexpected dimensions or mask count')
    for p,c in paired:
        if (p is None) != (c is None) or (p is not None and not (math.isfinite(p) and math.isfinite(c) and p>0 and c>0)):
            raise ValueError('Unexpected mask or non-positive/non-finite source cell')
    return {
        'schema_version':1, 'model_id':MODEL_ID,
        'status':'implementation_candidate_for_controlled_field_trial_not_field_calibrated',
        'scope':'one V2 ODU in heating mode; V2 old and new share performance by owner decision',
        'units':{'frequency':'Hz','ambient':'degC','supply':'degC','pth':'W','cop':'W/W','pel':'W'},
        'dimension_order':['supply','ambient','frequency'],
        'shape':[8,17,10], 'valid_nodes':590, 'masked_nodes':770,
        'source':{'firmware':'CiC 4.2.0 supplied ELF', 'elf_sha256':ELF_SHA256,
                  'file_offsets':{'frequency':'0x200588','ambient':'0x2005a0','supply':'0x200628',
                                  'power_literals':'0x200668','cop_literals':'0x202af8'},
                  'constructor_va':'0x13498c', 'constructor_logical_rows_per_quantity':136,
                  'literal_row_width_bytes':80, 'unique_literal_rows_per_quantity':117,
                  'logical_to_literal_row':ROW_MAP},
        'axes':{'frequency_hz':FREQ,'ambient_c':AMB,'supply_c':SUP},
        'interpolation':{'method':'piecewise trilinear Pth and COP; Pel=Pth/COP AFTER interpolation',
                         'mask':'any strictly positive-weight missing corner invalidates query; zero-weight corners ignored',
                         'outside_domain':'unavailable; optional explicit guarded low-supply boundary estimate in adapter',
                         'axis_precision':'double; preserve epsilon boundaries; do not average or merge rows',
                         'off':'0 Hz gives incremental Pth=0, Pel=0, COP unavailable; auxiliary electricity separate'},
        'pth_w':power, 'cop':cop,
    }

def f32(value: float) -> float:
    return struct.unpack('<f',struct.pack('<f',value))[0]

def cpp_float(value: float | None) -> str:
    if value is None: return 'MISSING'
    s = format(f32(value), '.9g')
    if '.' not in s and 'e' not in s.lower(): s += '.0'
    return s+'f'

def render_header(m: dict) -> str:
    lines=['// Generated by scripts/research/build_v2_model.py. Do not edit numeric data.',
           '// Source ELF SHA256: '+ELF_SHA256, '#pragma once', '#include <limits>',
           'namespace oq_v2_model::data {',
           'inline constexpr char MODEL_ID[] = "'+MODEL_ID+'";',
           'inline constexpr float MISSING = std::numeric_limits<float>::quiet_NaN();']
    for name, values in [('FREQUENCY_HZ',FREQ),('AMBIENT_C',AMB),('SUPPLY_C',SUP)]:
        lines += ['inline constexpr double '+name+'['+str(len(values))+'] = {',
                  '    '+', '.join(repr(float(v)) for v in values), '};']
    for field,name in [('pth_w','PTH_W'),('cop','COP')]:
        lines += ['inline constexpr float '+name+'[8][17][10] = {']
        for i,plane in enumerate(m[field]):
            lines += ['  {  // Supply '+str(SUP[i])+' degC']
            lines += ['    {'+', '.join(cpp_float(v) for v in row)+'},' for row in plane]
            lines += ['  },']
        lines += ['};']
    lines += ['}  // namespace oq_v2_model::data','']
    return '\n'.join(lines)

def write_outputs(m: dict, out: Path) -> None:
    (out/'model').mkdir(parents=True,exist_ok=True)
    (out/'include').mkdir(parents=True,exist_ok=True)
    (out/'model/v2_heating_cic420_r1.json').write_text(json.dumps(m,indent=2,allow_nan=False)+'\n')
    (out/'include/hp_v2_model_data.h').write_text(render_header(m))
    with (out/'model/v2_heating_nodes.csv').open('w',newline='') as stream:
        w=csv.writer(stream)
        w.writerow(['supply_index','ambient_index','frequency_index','supply_c','ambient_c','frequency_hz',
                    'valid','pth_w','cop','pel_w_at_node','power_file_offset','cop_file_offset','literal_row'])
        for s,tc in enumerate(SUP):
            for a,ta in enumerate(AMB):
                row=ROW_MAP[s][a]
                for f,hz in enumerate(FREQ):
                    p,c=m['pth_w'][s][a][f],m['cop'][s][a][f]
                    w.writerow([s,a,f,tc,ta,hz,int(p is not None),p,c,p/c if p is not None else None,
                                hex(0x200668+80*row+8*f),hex(0x202af8+80*row+8*f),row])

def main() -> None:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--elf',type=Path,required=True)
    parser.add_argument('--out',type=Path,required=True)
    args=parser.parse_args()
    try:
        m=extract(args.elf);write_outputs(m,args.out)
    except (OSError,ValueError,struct.error) as exc:
        parser.exit(1,f'ERROR: {exc}\n')
    print(f'{MODEL_ID}: 1360 nodes, 590 valid / 770 masked; outputs in {args.out}')

if __name__=='__main__': main()
